apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello

spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: name
              image: busybox
              args:
                - /bin/sh
                - -c
                - date;echo hello from the K8S cluter;
          restartPolicy: OnFailure
  schedule: "*/1 * * * *"