# permissions for end users to view cola.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cola-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app
    app.kubernetes.io/part-of: app
    app.kubernetes.io/managed-by: kustomize
  name: cola-viewer-role
rules:
- apiGroups:
  - apps.cola.com
  resources:
  - cola
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.cola.com
  resources:
  - cola/status
  verbs:
  - get
