---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.cola.com
  resources:
  - cola
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.cola.com
  resources:
  - cola/finalizers
  verbs:
  - update
- apiGroups:
  - apps.cola.com
  resources:
  - cola/status
  verbs:
  - get
  - patch
  - update
