# permissions for end users to edit coffees.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: coffee-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: coffeeoperator
    app.kubernetes.io/part-of: coffeeoperator
    app.kubernetes.io/managed-by: kustomize
  name: coffee-editor-role
rules:
- apiGroups:
  - coffeeapp.coffee.domain
  resources:
  - coffees
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coffeeapp.coffee.domain
  resources:
  - coffees/status
  verbs:
  - get
